### ISSUE TITLE
references to https://fedorahosted.org/pagure/

### ISSUE THREAD

**Issue by ktdreyer** [pypingou/pagure#11]
The code has a couple references to the "pagure" project on fedorahosted.org, which is presently a 404 error.

`pagure/templates/master.html` refers to https://fedorahosted.org/pagure/

`doc/deployment.rst` refers to http://git.fedorahosted.org/git/pagure.git

`setup.py` has references as well

**Comment by pypingou** [comment]
We should use pagure.io instead of fedorahosted indeed, would you want to fix these?

We could just use pagure for this ;-)

**Comment by pypingou** [comment]
Fixed in https://github.com/pypingou/pagure/commit/0b5a62183979d7d11b04d5ad044b6628a7045e28
