### ISSUE TITLE
Adopt to changes in libgit2 0.23.0

### ISSUE THREAD

**Issue by ignatenkobrain** [pypingou/pagure#13]
https://github.com/libgit2/libgit2/releases/tag/v0.23.0

Actually python-pygit2 has no releases with 0.23.0 API changes, but I updated libgit2 to 0.23.0 in F23&Rawhide and cherry-picked patch from upstream to support that API, so pagure probably will not work there. So it's good start for future ;)

**Comment by pypingou** [comment]
You should report it there: https://pagure.io/pagure

And this is a recurrent problem with pygit2 which really makes me want to move away from it...
